[package]
name = "simuverse"
version = "0.1.0"
authors = ["Jinlei Li <jinleili0@outlook.com>"]
edition = "2021"
rust-version = "1.64"

[dependencies]
# 兼容 egui-winit 0.21
app-surface = { git = "https://github.com/jinleili/wgpu-in-app", rev = "8271c28" }
egui = { version = "0.21.0", default-features = false }
egui-wgpu = { version = "0.21.0" }
egui-winit = { version = "0.21.0" }
winit = { version = "0.28" }
egui_extras = { version = "0.21.0", optional = true }

bytemuck = "1.4"
cfg-if = "1"
env_logger = "0.9"
futures-intrusive = "0.4"
log = "0.4"
wgpu = "0.15"
png = "0.17"
pollster = "0.2"
rand = "0.8"
image = { version = "*" }
nalgebra-glm = "*"
glam = "0.22"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
wasm-bindgen-futures = "0.4.33"
web-sys = { version = "0.3.60", features = ["Document", "Window", "Element"] }
