[package]
name = "simuverse"
version = "0.1.1"
authors = ["Jinlei Li <jinleili0@outlook.com>"]
edition = "2021"
rust-version = "1.76"

[dependencies]
app-surface = { version = "0.4.2" }
# app-surface = { path = "../../idroid/wgpu-in-app/app-surface" }
# egui = { git = "https://github.com/emilk/egui", rev = "ded8dbd", default-features = false }
# egui_extras = { git = "https://github.com/emilk/egui", package = "egui_extras", rev = "ded8dbd" }
# egui-wgpu = { git = "https://github.com/emilk/egui", package = "egui-wgpu", rev = "ded8dbd" }
# egui-winit = { git = "https://github.com/emilk/egui", package = "egui-winit", rev = "ded8dbd", default-features = false }
egui = { version="0.28.1", default-features = false }
egui_extras = { version="0.28.1" }
egui-wgpu = { version="0.28.1" }
egui-winit = { version="0.28.1", default-features = false }

webbrowser = { version = "1.0.1" }
# 需要 egui 先升级到 winit 0.30 后才能使用
winit = { version = "0.29.10" }
raw-window-handle = "0.6"
wgpu = "0.20"
glam = "0.27"
# syntax_highlighting 需要 enum-map
enum-map = { version = "2", features = ["serde"] }
bytemuck = "1.15"
env_logger = "0.10"
log = "0.4"
rand = "0.8"
image = { version = "*" }
cfg-if = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
pollster = "0.3"
# truck dependencies
instant = { version = "0.1.12", features = ["now"] }
rayon = "1.8"
rustc-hash = "1.1.0"
serde_json = "1.0.93"
truck-base = { version = "0.4.0" }
truck-meshalgo = { version = "0.3.0" }
truck-modeling = { version = "0.5.1" }
truck-polymesh = { version = "0.5.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
instant = { version = "0.1.12", features = ["now", "wasm-bindgen"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0"
js-sys = "0.3.67"
reqwest = "0.11.15"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.40"
web-sys = { version = "0.3.67", features = [
    "Blob",
    "Document",
    'Element',
    'HtmlElement',
    "Node",
    "NodeList",
    "HtmlCanvasElement",
    "OffscreenCanvas",
    "ImageBitmap",
    "ImageBitmapRenderingContext",
    "Url",
    "Window",
    "WorkerGlobalScope",
    "XmlHttpRequest",
    # Needed by webgpu_sys
    "Event",
    "EventTarget",
] }